sudo: required
language: node_js
dist: xenial

node_js:
  - node

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make
  - make test

# after_success:
#   - chmod 600 .travis/deploy_key.pem
#   - ssh-add .travis/deploy_key.pem
#   - git remote add deploy ssh://yakk@test.yakk.io/yakk.git
#   - git push deploy
addons:
  firefox: latest-nightly
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
