sudo: false
dist: trusty

language: python

services:
  - postgresql

python:
  - "3.6"

matrix:
  include:
    - python:
      - "3.6"
    - env:
      - DATABASE_URL=psql://postgres:/travis_ci_test
      - SECRET_KEY=travis_secret_key
      - COVERAGE=1
      before_script:
      - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - cd server
        - make test

    - node_js:
      - "node"
      env:
      - NODE_ENV=test
      - COVERAGE=1
      addons:
        firefox: latest-nightly
        apt:
          packages:
            google-chrome-stable
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - cd client
        - make test