sudo: required
language: node_js
node_js:
  - node
before_install:
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
  - sudo apt-get update
  - sudo apt-get install google-chrome-stable
  - export CHROME_BIN=/usr/bin/google-chrome

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make
  - make test

# after_success:
#   - chmod 600 .travis/deploy_key.pem
#   - ssh-add .travis/deploy_key.pem
#   - git remote add deploy ssh://yakk@test.yakk.io/yakk.git
#   - git push deploy
addons:
  firefox: latest-nightly