sudo: required
language: node_js
dist: xenial

node_js:
  - node

before_install:
  - sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list'
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  - sudo apt update
  - sudo apt install google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

env:
  - TEST_DIR=client
  - TEST_DIR=server

script:
  - make
  - cd $TEST_DIR && COVERAGE=1 make test

# after_success:
#   - chmod 600 .travis/deploy_key.pem
#   - ssh-add .travis/deploy_key.pem
#   - git remote add deploy ssh://yakk@test.yakk.io/yakk.git
#   - git push deploy
addons:
  firefox: latest-nightly
