sudo: false
dist: trusty

language: python
python:
  - "3.6"

node_js:
  - "node"

services:
  - postgresql

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - NODE_ENV=test
    - DATABASE_URL=psql://postgres:/travis_ci_test
    - SECRET_KEY=travis_secret_key

  matrix:
  - TEST_DIR=client
  - TEST_DIR=server


script:
  - make
  - cd $TEST_DIR && COVERAGE=1 make test

addons:
  firefox: latest-nightly
  apt:
    packages:
      google-chrome-stable
