language: node_js
node_js:
  - node
before_script:
  - npm install -g bower gulp
  - bower install
script: gulp
before_install:
  - openssl aes-256-cbc -K $encrypted_6b49691c1ab4_key -iv $encrypted_6b49691c1ab4_iv
    -in .travis/deploy_key.pem.enc -out deploy_key.pem -d

after_success:
  - chmod 600 .travis/deploy_key.pem
  - ssh-add .travis/deploy_key.pem
  - git remote add deploy ssh://yakk@test.yakk.io/yakk.git
  - git push deploy
